[package]
name = "loopswap"
version = "2.6.1"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common loopswap types"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.13.2" } 
cosmwasm-storage = { version = "1.0.0" }
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
schemars = "0.8.10"
serde = { version = "1.0.132", default-features = false, features = ["derive"] }
protobuf = { version = "2", features = ["with-bytes"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
